apiVersion: 1
datasources:
  - orgId: 1
    name: Prometheus
    type: prometheus
    typeLogoUrl: ''
    access: proxy
    url: http://localhost:9090
    password: ''
    user: ''
    database: ''
    basicAuth: false
    basicAuthUser: ''
    basicAuthPassword: ''
    withCredentials: false
    isDefault: true
    jsonData:
      httpMethod: POST
    secureJsonFields: {}
    version: 3
    readOnly: false
